--- #YAML:1.0
name:                Acme-CPANAuthors-Not
version:             0.01
abstract:            We are not CPAN authors
license:             perl
author:              
    - Steve Fink <sfink@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Acme::CPANAuthors:             0.01
    Test::More:                    0.47
    Test::UseAllModules:           0.09
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
